apiVersion: v1
kind: Pod
metadata:
  name: pod-env-secret
  namespace: default
spec:
  containers:
  - name: cnt1
    image: busybox
    args: ['/bin/sh', '-c', 'env']
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: secret1
          key: username
    - name: DB_PWD
      valueFrom:
        secretKeyRef:
          name: secret1
          key: password
      