apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-secret
  namespace: default
spec:
  volumes:
  - name: vol1
    secret:
      secretName: secret1
      items:
      - key: username
        path: user.conf
      - key: password
        path: pwd.secret
  containers:
  - name: pod2
    image: busybox
    command: ['/bin/sh', '-c', 'cd /etc/data/ && ls -l']
    volumeMounts:
    - name: vol1
      mountPath: /etc/config/mysql
      