apiVersion: v1
kind: Service
metadata:
  name: headless-demo0
  namespace: default
  labels:
    svc: headless
    app: nginx
spec:
  selector:
    app: myapp
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8082
    name: nginx-svc
    targetPort: 80
    protocol: TCP