apiVersion: v1
kind: Service
metadata:
  name: headless-demo1
  namespace: default
  labels:
    app: nginx
    svc: headless
spec:
  selector:
    app: nginx-web02
  type: ClusterIP # ClusterIP, NodePort, LoadBalance, ExternalName
  clusterIP: None
  ports:
  - port: 8083
    protocol: TCP
    name: httpd-port02
    targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo01
  namespace: default
  labels:
    ctl: sset
    app: nginx
spec:
  serviceName: headless-demo0
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: ["nginx-web02"]
  template:
    metadata:
      namespace: default
      labels:
        app: nginx-web02
    spec:
      containers:
      - name: nginx-web-test
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
        
    
  