apiVersion: v1
kind: Pod
metadata:
  name: pod-localpv
spec:
  volumes:
  - name: localpv
    persistentVolumeClaim:
      claimName: pvc-locapv
  containers:
  - name: ng
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: localpv
      mountPath: "/usr/share/nginx/html"