apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  hostPath:
    path: /data/k8s/test/hostpath
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
    