apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests: 
      storage: 500M
