apiVersion: v1
kind: Pod
metadata:
  name: pod-hostport-demo
  labels:
    zjqi.top/nginx: test
spec:
  containers:
  - name: nginx-pod-hostport
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: httpd
      containerPort: 80
      hostPort: 8087
      hostIP: 0.0.0.0
      protocol: TCP