apiVersion: v1
kind: Pod
metadata:
  name: nginx-use-hostnetwork-demo
  labels:
    zjqi.top/nginx: test
spec:
  hostNetwork: True
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: httpd
      containerPort: 8088
      hostIP: 0.0.0.0
      protocol: TCP
      # hostPort: 8088
