apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-mon

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole  # 因为要prometheus要访问集群额所有资源，所以是clusterrole
metadata:
  name: prometheus-clusterrole
  namespace: kube-mon
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
    - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-clsrolebinding
  namespace: kube-mon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-clusterrole
subjects:
- name: prometheus
  kind: ServiceAccount
  namespace: kube-mon