apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: kube-mon
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: prometheus-web
    port: 9090
    targetPort: http